from enum import Enum
class SyntaxError(Enum):

    READ_OPEN_PARENTHESES = 1.1
    READ_VAR = 1.2
    READ_CLOSE_PARENTHESES = 1.3
    RETURN_OPEN_PARENTHESES = 2.1
    RETURN_EXPRESSION = 2.2
    RETURN_CLOSE_PARENTHESES = 2.3
    WRITE_OPEN_PARENTHESES = 3.1
    WRITE_EXPRESSION = 3.2
    WRITE_CLOSE_PARENTHESES = 3.3
    CALL_FUNCTION_CLOSE_PARENTHESES = 4.1
    CALL_FUNCTION_PARAMETERLIST = 4.2

